--  Write a query to display employee name, annual salary and annual salary after 10% deduction.
select ename, (sal*12) as "ann sal",(sal*12*0.9) from emp;

--  Write a query to display employee name, job and salary after deducting 100 from salary.
SQL> select ename, job ,(sal-100) as "salary after penalty" from emp;
--

SELECT ename AS "EMPLOYEE NAME", job AS "DESIGNATION", (sal - 100) AS "SALARY AFTER PENALTY"FROM
  6    emp;

WAQTD NAMES OF ALL THE EMPLOYEES.
SELECT ename FROM emp;

WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL
THE EMPLOYEES
SELECT empno, deptno FROM emp;

WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES
SELECT ename, hiredate FROM emp;


.WAQTD NAME , JOB AND SALARY GIVEN ALL THE
EMPLOYEES.
SELECT ename, job, sal FROM emp;


.WAQTD DNAMES PRESENT IN DEPARTMENT TABLE.
SELECT dname FROM dept;

WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR
ANNUAL SALARY.
SELECT ename, (sal * 12) AS "ANNUAL SALARY" FROM emp;

WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG
WITH AN ANNUALBONUS OF 2000.
SELECT emp.*, 2000 AS "ANNUAL BONUS" FROM emp;


.WAQTD NAME SALARY AND SALARY WITH A HIKE OF
10%.
SELECT ename, sal, (sal * 1.1) AS "SALARY WITH HIKE" FROM emp;

5.WAQTD NAME AND SALARY WITH DEDUCTION OF 25%.
SELECT ename, sal, (sal * 0.75) AS "SALARY AFTER DEDUCTION" FROM emp;

6.WAQTD NAME AND SALARY WITH MONTHLY HIKE OF 50.
SELECT ename, sal, (sal + 50) AS "SALARY AFTER MONTHLY HIKE" FROM emp;

7.WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION
OF 10%.
SELECT ename, (sal * 12) AS "ANNUAL SALARY", (sal * 12 * 0.9) AS "ANNUAL SALARY AFTER DEDUCTION" FROM emp;

8.WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE
(SAL+COMM).
SELECT ename, (sal + NVL(comm, 0)) AS "TOTAL SALARY" FROM emp;

9.WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH
ANNUAL SALARY.
SELECT emp.*, (sal * 12) AS "ANNUAL SALARY" FROM emp;

10.WAQTD NAME AND DESIGNATION ALONG WITH 100
PENALTY IN SALARY.
SELECT ename AS "EMPLOYEE NAME", job AS "DESIGNATION", (sal - 100) AS "SALARY AFTER PENALTY" FROM emp;
