select deptno from emp where ename  = 'MILLER';


SELECT LOC FROM DEPT WHERE DEPTNO  = (SELECT DEPTNO FROM EMP WHERE ENAME= 'ADAMS');


 select dname  from DEPT where deptno  = (select deptno from emp where ename = 'MILLER');


 SELECT COUNT(*) FROM EMP WHERE DEPTNO  = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'D3');


  SELECT * FROM EMP WHERE JOB = 'MANAGER' AND  DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME  = 'ACCOUNTING');


   SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME  = 'MILLER') AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');


    SELECT MAX(SAL) FROM EMP WHERE DEPTNO= (SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS');


     select dname from DEPT where DEPTNO  =(SELECT DEPTNO FROM EMP WHERE ENAME= 'SMITH');


      SELECT DNAME , LOC FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'KING');


       SELECT LOC FROM DEPT
  2  WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE EMPNO = 7902);


  SELECT * FROM DEPT ;


   SELECT * FROM SALGRADE ;


   SELECT * FROM EMP ;


    SELECT DNAME FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE JOB = 'PRESIDENT');


    SELECT ENAME FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING');


     SELECT ENAME, SAL FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO');


      SELECT EMP.*, SAL*12 FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');


       SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING') ;


       SELECT ENAME, SAL, JOB, HIREDATE FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'KING') AND DEPTNO = (SELECT DEPTNO  FROM DEPT WHERE DNAME = 'OPERATIONS');


        SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE SAL = 800);


        SELECT LOC FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE DEPTNO = 40 AND COMM IS NOT NULL);


        SELECT ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP );


        SELECT ENAME FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP);


        SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE < (SELECT MIN(HIREDATE) FROM EMP);


        SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP);


        SELECT ENAME, COMM FROM EMP WHERE COMM = (SELECT MIN(COMM) FROM EMP);

        